export const confessionals = {
  "struggles": [
    "Oh honey, I am STRUGGLING. This is NOT my forte.",
    "I thought I had this in the bag… turns out, the bag is on fire.",
    "This challenge is really kicking my padded ass.",
    "I’m trying to keep it together, but inside I am SCREAMING!",
    "I have NO idea what I’m doing, and I think everyone can tell.",
    "I came here to slay, but right now? I’m just PRAYING.",
    "Why did I think I could do this? Who let me audition??",
    "Okay… deep breaths. I can pull this together… right? RIGHT?!",
    "Y’all, this is going downhill faster than my last relationship.",
    "I feel like a deer in headlights… but make it fashion.",
    "I didn’t come here to fail… but failure is coming for me!",
    "Not to be dramatic, but this is my personal nightmare.",
    "Can someone roll the credits? Because I am DONE.",
    "Ru, if you can hear me… HELP.",
    "I am just holding on for dear life at this point.",
    "I know I’m supposed to be having fun… but where’s the fun??",
    "Everyone else is thriving, and I’m over here like, 'Can I get a do-over?'",
    "If I survive this challenge, I’m buying myself a drink. If I don’t, someone better pour one out for me.",
    "I was expecting a challenge… but not an ASSASSINATION.",
    "The only thing I’m serving right now is CONFUSION.",
    "I feel like I’m in an episode of 'Drag Race: Disaster Edition.'",
    "I’m trying to be professional, but I just wanna cry in the corner.",
    "They said this would be fun. They LIED.",
    "You ever just wanna vanish? Because SAME.",
    "If stress was a drag queen, she’d be sitting in my seat.",
    "I should have brought a backup plan… or three.",
    "This is NOT going as planned. Actually, did I even HAVE a plan?",
    "I am THIS close to just making a run for the exit.",
    "In my head, this was gonna go SO much better.",
    "I’m sweating, I’m shaking, I’m spiraling… but I still look FABULOUS.",
    "Right now, I am questioning every decision that brought me here.",
    "If this was a ‘Hot Mess’ challenge, I’d be winning.",
    "At this point, I’m just hoping for a miracle.",
    "Maybe if I just smile, no one will notice I’m drowning?",
    "Send help. And maybe some glitter, because this is a MESS.",
    "I came here to slay… but I might be sashaying away.",
    "I’m not saying I’m in trouble, but if you listen closely, you can hear RuPaul writing my name on a lipstick.",
    "What’s the opposite of slaying? Because that’s what I’m doing.",
    "I should be worried, but honestly? I’m too confused to panic.",
    "This is giving… first episode elimination energy, and I don’t like it.",
    "I swear I’m talented, I just need another challenge. Or a time machine.",
    "I am holding onto my wig for dear life, because this is CHAOS.",
    "If struggling was an Olympic sport, I’d have a gold medal right now.",
    "I didn’t expect to struggle THIS much, but here we are!",
    "In my head, I’m winning. In reality? Not so much.",
    "The only thing getting eliminated right now is my confidence.",
    "I love a good challenge… but I also love knowing what I’m doing.",
    "I hope the judges see potential, because that’s all I’ve got right now.",
    "I would love to say ‘I got this!’ but that would be a LIE."
  ],
  "confidence": [
    "Oh honey, this challenge was MADE for me!",
    "I’m about to eat this up and leave NO crumbs.",
    "Confidence? Check. Talent? Check. Winning energy? CHECK!",
    "I didn’t come here to play—I came here to SLAY!",
    "I hope the other girls brought sunglasses, because I’m about to SHINE.",
    "This challenge is right up my alley. If I don’t win, it’s rigged!",
    "Queens, take notes. This is how it’s DONE!",
    "Let’s be real—I was born for this moment.",
    "I can already hear Ru saying, ‘Condragulations, you are the winner of this week’s challenge!’",
    "Call the producers and tell them to wrap it up, because I just WON this challenge.",
    "I’m giving talent, I’m giving charisma, I’m giving WINNER energy!",
    "I didn’t come to compete, I came to COLLECT awards.",
    "Sorry, ladies, but tonight… the spotlight is MINE.",
    "I’ve been waiting for this challenge since I got here, and I am READY!",
    "I have the skills, the confidence, and the beauty. What could go wrong? (Knock on wood!)",
    "This challenge is practically my drag superpower.",
    "Oh, this is going to be too easy! Let me just sit back and enjoy.",
    "The judges are about to be GAGGED. Mark my words.",
    "I hope the other girls have a backup plan, because I’m about to steal this win!",
    "If the category is excellence, then I’m already in the Hall of Fame.",
    "All I have to do is show up and be myself. That’s how you WIN!",
    "I don’t even need luck—I just need the judges to keep their eyes open!",
    "They might as well start engraving my name on that trophy right now.",
    "Look, I love my sisters, but I also love WINNING!",
    "I know talent when I see it, and guess what? I see it every time I look in the mirror.",
    "Is it cocky if it’s true? Because baby, I GOT THIS!",
    "I’m feeling my oats, my grains, and my WHOLE entire crop!",
    "This is the part where I say ‘I hope I do well,’ but let’s be real—I KNOW I will!",
    "I don’t just walk into a challenge, I OWN the challenge.",
    "Winning is a habit, and baby, I’m in my routine!",
    "You ever just KNOW you’re about to make history? Because same.",
    "I don’t do ‘safe.’ I do FABULOUS, and that’s exactly what I’m bringing today!",
    "They’re going to need a mop, because I am about to WIPE this competition!",
    "I was born ready for this moment, and the judges are about to find out why!",
    "This challenge is giving ‘meant to be,’ and I am READY to deliver!",
    "Queens, take notes. You’re about to witness a MASTERCLASS.",
    "Watch and learn, because I’m about to give a PERFORMANCE.",
    "I already have my winner’s speech prepared. Just saying!",
    "There’s confident, and then there’s ME right now!",
    "This challenge is a feast, and baby, I’m here to EAT!",
    "I just need to walk in there and BE myself. Easy win.",
    "When Ru said ‘good luck and don’t f*ck it up,’ I felt that… for the OTHER queens!",
    "I’m not worried. The real challenge is how I’ll react when they announce me as the winner!",
    "I’m bringing charisma, uniqueness, nerve, talent… and a trophy home tonight!",
    "Y’all better be watching, because I’m about to put on a SHOW!",
    "I’ve been waiting for a challenge like this. Let’s show them how it’s DONE!",
    "Confidence is key, and baby, I’ve got the MASTER KEY!",
    "The only thing I’m worried about is how to carry all these compliments I’m about to get!",
    "I’m not saying I’m winning this challenge… but I AM saying, start the drumroll!",
    "Tonight? It’s giving WINNER ENERGY. Period."
  ]
}
