export const eliminations = [
  "\"I may be leaving, but trust me, this is just the beginning of my reign.\"",
  "\"They got me this time, but honey, I’ll be back—and better than ever.\"",
  "\"This is not the end of my journey. It’s just a plot twist.\"",
  "\"I came, I slayed, I fought… and now, I’ll take my crown elsewhere.\"",
  "\"Okay, maybe I didn't snatch the crown, but I sure as hell snatched some hearts!\"",
  "\"I may not be the winner, but I walked out of here as a QUEEN.\"",
  "\"No regrets, no tears—just glitter and fabulous memories!\"",
  "\"You can eliminate me, but you can’t eliminate my legacy.\"",
  "\"I gave it my all, and that’s all that matters. Period.\"",
  "\"I may be sashaying away, but trust me, I’ll be back with a vengeance!\"",
  "\"Losing isn’t failure. It’s just another chapter in my fabulous story.\"",
  "\"This is just a stepping stone to my real success. Watch out, world!\"",
  "\"Drag Race might not be my destiny, but greatness definitely is.\"",
  "\"Well… I guess my crown will just have to wait a little longer!\"",
  "\"I may have lost the battle, but I’m winning the war of my life.\"",
  "\"Who needs a trophy when I already know I’m a star?\"",
  "\"Leaving is bittersweet, but honey, this queen is far from done!\"",
  "\"I didn’t make it to the end, but I made it HERE. And that means something.\"",
  "\"They’ll never forget my name, my looks, or my energy. Mission accomplished!\"",
  "\"This may be my exit, but darling, I’ll be making grand entrances everywhere else!\"",
  "\"I walked in as a queen, and I walk out as a legend.\"",
  "\"Not gonna lie, I wanted to win. But you know what? I already won in my heart.\"",
  "\"Sashay away? More like sashay into my next big opportunity!\"",
  "\"This is not a loss. It’s an intermission before the next big act in my life.\"",
  "\"RuPaul might have said goodbye, but the world is just saying hello!\""
]
