export const entrances = {
    "Fashion Queen": [
        "Strike a pose, because fashion is my full-time job and drama is my side hustle.",
        "I'm serving haute couture, darling. This season is all about me.",
        "I didn't come to play, I came to slay… straight off the Versace runway.",
        "Think Naomi, think Tyra, but with more attitude and a bigger budget.",
        "I'm not just a queen, I'm a walking Vogue editorial.",
        "Louis Vuitton? Chanel? Honey, I'm the whole fashion house.",
        "Why wear labels when I AM the brand?",
        "Serving looks sharper than a tailor’s needle.",
        "Runway-ready, drama steady. Let’s go, bitches.",
        "Category is: Legendary Supermodel, and the competition is CANCELLED.",
        "If you don’t know my name yet, just wait till Fashion Week.",
        "Who needs a crown when you have couture?",
        "I walked into the room and Karl Lagerfeld started sketching.",
        "I make Mugler look basic.",
        "One step onto this runway, and the world stops spinning.",
        "I don’t chase trends, trends chase me.",
        "My talent? Turning fabric into fantasies.",
        "My walk is worth more than your entire wardrobe, baby.",
        "Sorry, I can’t hear you over the sound of me being iconic.",
        "You can’t spell ‘fabulous’ without ME in it.",
        "I’m dripping in diamonds, drowning in glamour, and ready for war.",
        "Life’s a runway, and I’m always in first place.",
        "Fashion is pain, and honey, I’m suffering beautifully.",
        "Mirror, mirror on the wall… I already know I’m the fiercest of them all.",
        "Consider this your front-row ticket to my legacy."
    ],
    "Comedy Queen": [
        "Hope you brought extra lashes, because I’m about to snatch them ALL!",
        "If I had a dollar for every wig I've snatched, I'd be rich enough to afford human hair.",
        "You call it camp, I call it Tuesday.",
        "The only thing higher than my heels is my cholesterol.",
        "I'm not a regular queen, I’m a comedy queen... and a little bit of a mess.",
        "I didn’t come to make friends, but if you buy me a drink, I’ll reconsider.",
        "My talent? Making people laugh and stealing snacks from the werkroom.",
        "I put the ‘drama’ in drag... mostly because I can’t stop crying.",
        "Is this Drag Race or a roast? Because I'm about to flame all you bitches.",
        "Some girls lip sync for their lives, I just sync up my wifi and order pizza.",
        "Do I have a big personality? Yes. Do I have a big ass? Unfortunately, no.",
        "Get ready to gag, and not just because of my jokes.",
        "I didn’t come to win, I came to take naps in the Untucked lounge.",
        "You’re all serving fish, but I’m serving full-on seafood buffet, baby!",
        "Some queens are beauty queens, I’m a booger and proud.",
        "This dress? Oh, it's vintage. I found it at my aunt’s garage sale.",
        "I might not be pretty, but I am petty!",
        "My looks? Questionable. My humor? Undeniable.",
        "My contour is sharp, my jokes are sharper.",
        "Beauty fades, but my shade is eternal.",
        "I put the ‘extra’ in extravaganza, honey!",
        "Why walk the runway when I can waddle in style?",
        "Glamour? I don’t know her. But stupidity? We’re best friends.",
        "I may not be the best, but at least I’m not the worst… I think?",
        "Welcome to my TED Talk: How to Win Drag Race While Being Completely Chaotic."
    ],
    "Pageant Queen": [
        "Elegance, grace, and just a touch of shade. That’s the recipe for a winner.",
        "The crown isn’t won, it’s deserved. And I deserve everything.",
        "Perfection is a choice, and I make it every single day.",
        "A queen doesn’t need an introduction, but here I am.",
        "I came here to win, not to socialize.",
        "Winning is in my DNA, and I have the trophies to prove it.",
        "Some call it confidence, I call it reality.",
        "If poise was a competition, I’d already have my crown.",
        "Some queens rely on comedy, some on fashion. I rely on excellence.",
        "Pageantry is an art, and honey, I’m a masterpiece.",
        "I don’t need luck, I have talent and determination.",
        "Queens may rise and fall, but I remain flawless.",
        "Every detail is polished, every moment is planned.",
        "The difference between me and the other girls? Experience.",
        "They say no one’s perfect, but I’m here to change that.",
        "When I enter a room, even the walls start clapping.",
        "Winning isn’t everything—it’s the ONLY thing.",
        "This isn't a competition. It's my coronation.",
        "Elegance isn’t learned, it’s lived. And honey, I’m living.",
        "If confidence was a currency, I’d be a billionaire.",
        "Flawless execution. That’s the standard.",
        "Not all crowns are created equal, and neither are queens.",
        "A true queen never rushes—she simply arrives.",
        "I didn’t come to play; I came to reign.",
        "You may enter as competitors, but you’ll leave as my audience.",
        "The winner isn’t chosen, she’s destined.",
    ],
    "Theater Queen": [
        "To be or not to be? Honey, I’m already THE moment.",
        "Call me Barbra, call me Bette, just make sure you call me a star.",
        "This stage isn’t big enough for the both of us… oh wait, it is, I just need a spotlight.",
        "Meryl Streep who? This is MY leading role.",
        "I've played villains, I've played heroes, but this season, I'm playing WINNER.",
        "Did someone order a Broadway diva? Because I just arrived.",
        "All the world’s a stage, and I am the main character.",
        "I don’t need applause, but it’s highly encouraged.",
        "Welcome to my one-woman show, now playing for a limited time only.",
        "I was born for the stage, and now it’s time for my encore.",
        "Diva? Darling, I INVENTED the word.",
        "You might think you're the star, but I’m the whole production.",
        "It’s giving Elizabeth Taylor in her prime.",
        "Method acting? I don’t act—I just AM this fabulous.",
        "A performance so stunning, even the Oscars are jealous.",
        "I’ve studied the greats, now it’s time for them to study ME.",
        "My talent? Serving Broadway realness on a reality show budget.",
        "I can sing, I can dance, I can steal your crown.",
        "Drag is art, and I’m its masterpiece.",
        "I didn’t come to compete—I came to deliver a standing ovation performance.",
        "The stage is set, the lights are on, and I’m ready to steal the show.",
        "I’m not just a queen, I’m a Tony Award winner waiting to happen.",
        "The spotlight is my home, and the crown is my destiny.",
        "I’m not just a queen, I’m a living, breathing, singing spectacle.",
        "I didn’t come to play, I came to SING.",
        "I’m not just a queen, I’m a living, breathing, singing spectacle.",
    ],
    "Music Queen": [
        "Bitch, I’m Madonna—at least for tonight.",
        "I came to this competition like a wrecking ball.",
        "Baby, I was born this way—flawless.",
        "I'm feeling good as hell and ready to slay.",
        "Like a prayer, I’m gonna take you there.",
        "Hit me with your best shot, ‘cause I’m ready to win.",
        "I’m bringing sexy back… and the trophy too.",
        "You can’t hurry love, but you can hurry up and give me the crown.",
        "I came to drag race like a virgin… touched for the very first time!",
        "Honey, I don’t chase crowns. Crowns chase me – like a paparazzi flash!",
        "If Gaga taught me anything, it’s that a little drama never hurt nobody!",
        "I’m a material girl in a drag queen world, and I want it all!",
        "You can’t break my soul, but you can watch me break the competition!",
        "I’m not just a queen – I’m the whole damn Super Bowl halftime show!",
        "Let’s get loud, because silence was never an option!",
        "And I am telling you… I’m NOT going home first!",
        "I will survive… and take this crown while I’m at it!",
        "Sweet dreams are made of wigs, lashes, and drama!",
        "Call me Queen of the Night, ‘cause I’m about to snatch my throne!",
        "It’s raining talent… hallelujah!",
        "What’s love got to do with it? Nothing, if you don’t have charisma!",
        "Don’t stop me now… ‘cause I’m having a legendary moment!",
        "Respect? Oh, honey, I demand it!",
        "Let’s get physical… because I’m about to run laps around this competition!",
        "Voulez-vous… watch me snatch this trophy?!",
    ],
    "Unique Queen": [
        "I don’t think outside the box, I AM the box.",
        "If weird was an Olympic sport, I’d have 20 gold medals.",
        "I crawled out of the swamp, put on a wig, and now I’m here.",
        "I don’t do pretty… I do disturbing, and you’re welcome.",
        "If Tim Burton and Lady Gaga had a baby, it would be me.",
        "I’m the glitch in the matrix you didn’t know you needed.",
        "Normal? I don’t know her.",
        "My drag is like an abstract painting—confusing, but expensive.",
        "Some queens serve fish, I serve eldritch horror… bon appétit!",
        "I was sent from another dimension to win this crown… or destroy the universe.",
        "I’m what happens when a fever dream and a fashion show collide.",
        "You can’t spell ‘unique’ without ‘me’, but you can spell ‘terrified’, and that’s what you should be.",
        "I didn’t come to play, I came to make you question reality.",
        "Elegance? Never heard of her. Chaos? We’re best friends.",
        "I’m the final boss of drag, and you just unlocked hard mode.",
        "Some queens sparkle, I prefer to ooze.",
        "I look like a mistake, but a very expensive one.",
        "Ever seen a nightmare in heels? Well, now you have.",
        "I don’t fit in the box, I set it on fire.",
        "I’m the intersection of fashion, fear, and fever dreams.",
        "You call it weird, I call it revolutionary.",
        "I’m less ‘high fashion’ and more ‘what the hell is that?’",
        "If David Bowie and an alien had a baby, it would still be less weird than me.",
        "I didn’t dress up for this competition, I transcended into it.",
        "Some queens lip-sync, I summon demons."
    ]
}
