export const lipsync = {
  "losing": {
    "bigdifference": [
      "{name1} is commanding the stage, every movement sharp and precise. {name2} is giving her all, but it's clear who the judges have their eyes on.",
      "{name1} is a force of nature, embodying the song with every fiber of her being. Meanwhile, {name2} struggles to keep up, her energy faltering.",
      "It's like {name1} was born for this moment—she moves with confidence and grace. {name2} tries to match her energy, but the gap is undeniable.",
      "{name1} is hitting every beat with passion and precision, while {name2} stumbles to find her footing. The battle seems one-sided.",
      "{name1} is eating up the stage, giving the judges a show-stopping performance. {name2} looks nervous, and it shows.",
      "{name1} has the crowd in the palm of her hand, lipsyncing every lyric with passion. {name2} is present, but barely making an impact.",
      "From the first beat, {name1} claimed her moment, commanding attention. {name2} is trying, but she's fading into the background.",
      "{name1} is turning this lipsync into a full production—every move is calculated, every look is intentional. {name2} is struggling to keep up.",
      "While {name1} is giving a star performance, {name2} looks like she's trying to find her rhythm. The difference is clear.",
      "{name1} is embodying the song’s emotion with power and finesse. {name2} seems to be second-guessing every step.",
      "It's a spectacle! {name1} owns the stage with every move, while {name2} looks like she's holding on for dear life.",
      "You can see it in their eyes—{name1} is here to WIN. {name2} is fighting, but she’s falling behind.",
      "With every fierce movement, {name1} asserts dominance. {name2} is starting to look desperate, throwing out moves that feel unpolished.",
      "{name1} is electrifying! The judges are entranced, while {name2} seems to be getting lost in the shuffle.",
      "{name1} is living the lyrics, making the song her own. {name2} looks like she’s trying to catch up but keeps slipping.",
      "This is a masterclass in lipsync performance. {name1} is soaring, while {name2} is barely staying afloat.",
      "{name1} is putting on a SHOW, complete with drama, precision, and confidence. {name2} just can't match her energy.",
      "From start to finish, {name1} is in control. {name2} gives a few good moments, but she just can't compete.",
      "The judges are gagged! {name1} is serving passion and precision, while {name2} is visibly struggling.",
      "{name1} is captivating, holding every judge’s attention. {name2} is present, but barely making a dent.",
      "You can see {name1} feeling every lyric, while {name2} seems unsure of how to match her energy.",
      "{name1} is a full production, with flawless movement and intensity. {name2} is giving it her best, but it's not enough.",
      "{name1} has turned this performance into an experience. {name2} is struggling, her energy diminishing.",
      "As the final beats hit, it's clear—{name1} has dominated this lipsync. {name2} did her best, but it wasn't enough.",
      "The song ends, and there's no question—{name1} has taken this one with confidence and skill, leaving {name2} behind."
    ],
    "paired": [
      "Both queens are giving it everything! {name1} commands attention with sharp moves, but {name2} is keeping up, delivering raw emotion.",
      "{name1} starts off strong, but {name2} isn’t backing down. This is a true battle of wills.",
      "Every movement, every lyric—both {name1} and {name2} are locked in a fierce duel. The judges are watching closely.",
      "You can feel the intensity in the air! {name1} and {name2} are fighting for their spot, and neither one is giving in.",
      "It’s neck and neck! {name1} delivers dramatic flourishes, while {name2} counters with effortless cool.",
      "The tension is real! {name1} is giving performance energy, while {name2} is all about raw emotion. Who will win?",
      "One moment it feels like {name1} is leading, the next {name2} steals the spotlight. The judges are torn!",
      "Both queens are living in the moment, embodying the song in their own ways. This is going to be a tough decision.",
      "With each beat, {name1} and {name2} trade control of the stage. The competition is fierce!",
      "This is what a lipsync battle should be—equal parts passion, skill, and drama! {name1} and {name2} are going all out.",
      "{name1} brings energy, while {name2} plays with nuance. They’re telling two different stories, but both are captivating.",
      "The audience is on the edge of their seats! {name1} and {name2} are delivering in completely different ways.",
      "{name1} gives a high-energy performance, while {name2} goes for precision. It’s anyone’s game!",
      "This is a battle of technique versus emotion—{name1} stuns with choreography, but {name2} is feeling the music deeply.",
      "Back and forth, back and forth—{name1} and {name2} are making this one of the most thrilling lipsyncs yet!",
      "{name1} throws in an unexpected move, but {name2} counters with a dramatic moment. Who will come out on top?",
      "With each verse, the tension builds. {name1} is commanding, but {name2} has the judges gagged with her presence.",
      "Neither queen is backing down! {name1} owns the floor, while {name2} exudes charisma with every step.",
      "The song reaches its climax, and {name1} and {name2} are both pushing themselves to the limit.",
      "At this point, the judges will have a hard time picking a winner. {name1} and {name2} are both fighting hard!",
      "It’s a stunning duel! {name1} nails every move, but {name2} delivers heart and soul.",
      "As the final chorus plays, {name1} and {name2} are both giving unforgettable performances. This one will be close!",
      "This lipsync could go either way! {name1} stuns with precision, while {name2} captivates with raw energy.",
      "The judges are whispering to each other—who will they choose? Both {name1} and {name2} have left their souls on that stage.",
      "The song ends, and both queens strike their final pose. The decision is in RuPaul’s hands now..."
    ],
  },
  "winning": {
    general: [
      "\"I was NOT ready to pack my bags, honey! That stage belongs to me.\"",
      "\"I fought tooth and nail for this moment, and baby, I ain't going nowhere!\"",
      "\"That was a battle, but guess what? I came, I slayed, I stayed.\"",
      "\"When the music started, I knew: this was MY moment to shine.\"",
      "\"I had no other choice but to turn it out. And look at me now!\"",
      "\"This was my redemption. I needed this, and I made it happen.\"",
      "\"I felt that performance in my soul. There was no way I was leaving tonight!\"",
      "\"I gave everything I had on that stage, and baby, it paid off!\"",
      "\"All the doubters can stay quiet now. I’m still standing!\"",
      "\"I saw my life flash before my eyes, and I snatched it right back.\"",
      "\"They thought I was done? Honey, I’m just getting started!\"",
      "\"The only thing getting eliminated tonight was that song, and I ATE IT UP!\"",
      "\"That was the most intense two minutes of my life, and I left it all on the stage.\"",
      "\"It was either win or go home, and trust me, I am NOT ready to go home.\"",
      "\"That was no ordinary lipsync—that was a drag WAR, and I won!\"",
      "\"I could feel my sisters rooting for me, and I did this for all of us.\"",
      "\"When Ru said my name, I swear I felt my heart start beating again!\"",
      "\"I might have been on the bottom, but I just proved why I belong at the top!\"",
      "\"This was my moment, and I seized it with every ounce of energy I had.\"",
      "\"That was a fight for survival, and I am one hell of a fighter!\"",
      "\"I turned that lipsync into a full-blown concert. Call me the headliner!\"",
      "\"The power, the passion, the performance… I was born for that stage!\"",
      "\"I feel invincible right now! That was everything I dreamed of and more.\"",
      "\"My adrenaline is still through the roof! I knew I had to slay, and I did just that.\"",
      "\"That was the most pressure I’ve ever felt, but pressure makes diamonds, baby!\""
    ],
    "assassin": [
      "\"I was NOT ready to pack my bags, honey! That stage belongs to me.\"",
      "\"I fought tooth and nail for this moment, and baby, I ain't going nowhere!\"",
      "\"That was a battle, but guess what? I came, I slayed, I stayed.\"",
      "\"When the music started, I knew: this was MY moment to shine.\"",
      "\"I had no other choice but to turn it out. And look at me now!\"",
      "\"This was my redemption. I needed this, and I made it happen.\"",
      "\"I felt that performance in my soul. There was no way I was leaving tonight!\"",
      "\"I gave everything I had on that stage, and baby, it paid off!\"",
      "\"All the doubters can stay quiet now. I’m still standing!\"",
      "\"I saw my life flash before my eyes, and I snatched it right back.\"",
      "\"They thought I was done? Honey, I’m just getting started!\"",
      "\"The only thing getting eliminated tonight was that song, and I ATE IT UP!\"",
      "\"That was the most intense two minutes of my life, and I left it all on the stage.\"",
      "\"It was either win or go home, and trust me, I am NOT ready to go home.\"",
      "\"That was no ordinary lipsync—that was a drag WAR, and I won!\"",
      "\"I could feel my sisters rooting for me, and I did this for all of us.\"",
      "\"When Ru said my name, I swear I felt my heart start beating again!\"",
      "\"I might have been on the bottom, but I just proved why I belong at the top!\"",
      "\"This was my moment, and I seized it with every ounce of energy I had.\"",
      "\"That was a fight for survival, and I am one hell of a fighter!\"",
      "\"I turned that lipsync into a full-blown concert. Call me the headliner!\"",
      "\"The power, the passion, the performance… I was born for that stage!\"",
      "\"I feel invincible right now! That was everything I dreamed of and more.\"",
      "\"My adrenaline is still through the roof! I knew I had to slay, and I did just that.\"",
      "\"That was the most pressure I’ve ever felt, but pressure makes diamonds, baby!\""
    ]
  }
}