export const maxidescriptions = {
  "Acting Challenge": "Queens must showcase their theatrical skills by performing in scripted scenes, often filled with campy humor, exaggerated drama, or parody of famous movies and TV shows. Strong acting, comedic timing, and the ability to sell a character are crucial.",
  "Ball Challenge": "A high-fashion extravaganza where queens must present three distinct runway looks based on a central theme. One of the looks is usually a ‘design and create’ challenge, testing their sewing skills and creativity under pressure.",
  "Choreography Challenge": "Queens must learn and perform intricate choreography in a group or solo performance. The challenge tests their rhythm, ability to follow steps, and overall stage presence. Some queens shine, while others struggle to keep up with the beat!",
  "Commercial Challenge": "Contestants must create and star in their own comedic or promotional commercial. The challenge focuses on branding, creativity, humor, and the ability to deliver a memorable performance that sells a ridiculous product or personal brand.",
  "Design Challenge": "A true test of sewing and creativity, queens must construct a head-to-toe look from unconventional materials or limited resources. Innovation and execution are key, as a poor design can quickly land a queen in the bottom.",
  "Girl Group Challenge": "Contestants are split into groups and must record, choreograph, and perform an original song, often with different verses. They need to write strong lyrics, serve pop-star charisma, and bring synergy to their team’s performance.",
  "Improvisation Challenge": "With no script and little time to prepare, queens must think fast and deliver comedic gold in an improv setting. Whether it’s an interview, talk show skit, or fake reality TV moment, their quick wit and chemistry with others are tested.",
  "Lip Sync Challenge": "Every queen must perform a high-energy lip sync number, bringing passion, moves, and emotional connection to the song. The ability to captivate an audience with a flawless sync and killer dance moves is crucial.",
  "Makeover Challenge": "Queens are paired with non-drag individuals—whether it be crew members, veterans, or family members—and must transform them into full-fledged drag personas. Cohesion between the makeover and the queen’s own style is key.",
  "Music Video Challenge": "Contestants must film and perform in a high-production music video, often featuring lip-syncing, choreography, and dramatic camera work. Queens must balance looking stunning, dancing on beat, and conveying pop-star energy.",
  "Photoshoot Challenge": "Strike a pose! Queens are tasked with delivering stunning editorial photos under challenging conditions, such as dynamic props, high winds, or underwater setups. The ability to serve face, angles, and editorial realness is tested.",
  "Rumix Challenge": "Queens must write and perform original verses for a remixed RuPaul song. They must also deliver choreography and stage presence, making sure they stand out while keeping up with the group dynamic.",
  "Runway Challenge": "A fashion-focused challenge where queens must serve a single iconic runway look based on a specific theme. The execution, styling, and overall presence determine who turns it out and who fades into the background.",
  "Rusical Challenge": "A full musical production where queens must sing, dance, and act in an over-the-top theatrical show. Contestants are assigned roles, and their ability to embody a character, hit musical beats, and shine in choreography is judged.",
  "Singing Challenge": "Live vocals only! Queens must perform a singing number, either solo or as part of a group. Whether belting out high notes or delivering comedy through song, this challenge separates the true vocalists from the rest.",
  "Snatch Game": "A fan-favorite challenge where queens impersonate a celebrity in a game-show format. Quick wit, strong character choices, and the ability to improvise hilarious responses separate the greats from the flops.",
  "Stand-Up Challenge": "Comedy queens, this is your time to shine! Queens must write and perform a stand-up routine in front of a live audience. Timing, delivery, and confidence on stage are essential to avoid total comedic disaster."
}
