export const rucritiques = {
  "positive": [
    "{name}, you were giving us the full fantasy, and mama, we were buying!",
    "{name}, your performance was a hit, and tonight, you're serving number one on the charts!",
    "{name}, your comedy had us gagging, and honey, that was no joke!",
    "{name}, your runway was so fierce, even Naomi Campbell would take a second look!",
    "{name}, your acting was award-worthy—Meryl Streep, who?",
    "{name}, your lip sync had more energy than a Beyoncé concert on opening night!",
    "{name}, tonight you didn’t just step it up, you leaped over the competition!",
    "{name}, your design skills are next level. I see Paris, I see Milan, I see YOU!",
    "{name}, your runway was pure magic. Harry Potter wishes he had those spells!",
    "{name}, that performance had more power than a Mariah Carey whistle note!",
    "{name}, your makeover was so good, I had to do a double take!",
    "{name}, your Snatch Game was so spot on, I thought we had a celebrity in the house!",
    "{name}, you turned the challenge inside out and upside down. Call it a Drag Race revolution!",
    "{name}, your presence on stage is like glitter—it sticks and we can’t get enough!",
    "{name}, your stand-up had us rolling on the floor—and not because we tripped on your gown!",
    "{name}, you took a risk and it paid off. The house is tipping their wigs to you!",
    "{name}, that lip sync was electrifying! I think my edges just got snatched!",
    "{name}, you danced like nobody was watching—but trust me, we ALL were!",
    "{name}, your look was so polished, I can see my reflection in it!",
    "{name}, you didn’t just bring the heat, you set the whole stage on fire!",
    "{name}, your humor was sharper than a stiletto heel, and just as deadly!",
    "{name}, tonight you were the definition of star power—bright, dazzling, and impossible to ignore!",
    "{name}, your performance was pure perfection—someone call the Louvre, we’ve got a masterpiece!",
    "{name}, you didn’t just meet the challenge, you redefined it!",
    "{name}, tonight, you were the moment, the mood, and the masterpiece!"
  ],
  "negative": [
    "{name}, your performance was not good, and impersonating Beyoncé is not your destiny, child.",
    "{name}, your runway was a Xanadu, but your performance was a Xanadon't.",
    "{name}, your Snatch Game was missing the snatch and the game!",
    "{name}, we were looking for a grand performance, but you barely made it past the starting line.",
    "{name}, your look was giving… last-minute craft project realness.",
    "{name}, your lip sync had about as much energy as a Sunday nap.",
    "{name}, we wanted a diva, but you gave us a disaster.",
    "{name}, your design skills had me questioning if you even own a sewing kit.",
    "{name}, this wasn't a tragedy, but it sure wasn't a comedy either.",
    "{name}, you were aiming for Broadway, but you barely made it off-Broadway.",
    "{name}, your stand-up was so painful, even my high heels feel more comfortable.",
    "{name}, your outfit was a crime—and I’m calling the fashion police.",
    "{name}, your performance needed CPR, because it was dead on arrival.",
    "{name}, tonight, you didn't just drop the ball, you kicked it out of the competition.",
    "{name}, your look was supposed to be camp, but it was giving summer camp craft project.",
    "{name}, we were hoping for a drag superstar, but you gave us a drag sidekick.",
    "{name}, I was looking for glamour, and all I found was glue gun glue.",
    "{name}, you gave us a performance… but unfortunately, no one was asking for it.",
    "{name}, tonight was supposed to be iconic, but you were more ironic.",
    "{name}, you came to the runway with a concept, but I think you left the execution backstage.",
    "{name}, this was your chance to shine, but girl, you barely flickered.",
    "{name}, your outfit had a story… unfortunately, it was a horror story.",
    "{name}, I was waiting for the gag, but all I got was a yawn.",
    "{name}, you tried to serve face, but it was more like a blank stare.",
    "{name}, I love a bold choice, but tonight, you made a bald choice… because you just snatched yourself bald."
  ]
}
