export const runways = [
  "Eleganza Extravaganza",
  "Night of a Thousand Madonnas",
  "Night of a Thousand Beyoncés",
  "Night of a Thousand Rihannas",
  "Night of a Thousand Lady Gagas",
  "Night of a Thousand Britneys",
  "Neon Fantasy",
  "Apocalyptic Couture",
  "Futuristic Fashion",
  "Intergalactic Diva",
  "Superheroes & Villains",
  "Gothic Elegance",
  "Angels & Demons",
  "Celestial Bodies",
  "Astrology Realness",
  "Under The Sea",
  "Deep Space Fantasy",
  "Sci-Fi Femme Fatale",
  "Enchanted Forest",
  "Royalty Extravaganza",
  "Mythical Creatures",
  "Elemental Elegance (Earth, Fire, Water, Air)",
  "Seasons Fashion (Spring, Summer, Fall, Winter)",
  "Floral Fantasy",
  "Met Gala Extravaganza",
  "Red Carpet Elegance",
  "High Fashion Editorial",
  "New York Fashion Week Realness",
  "Avant-Garde Eleganza",
  "50 Shades of Red",
  "Black & White Ball",
  "Metallic Glamour",
  "Disco Inferno",
  "Studio 54 Fantasy",
  "Burlesque Bombshell",
  "Pin-Up Perfection",
  "Dollhouse Divas",
  "Barbie Fantasy",
  "Candyland Couture",
  "Horror Glam",
  "Zombie Apocalypse",
  "Vampire Realness",
  "Witchy Woman",
  "Alien Invasion",
  "Time Traveler’s Ball",
  "Masquerade Ball",
  "Grecian Goddess",
  "Cleopatra Realness",
  "Rococo Extravaganza",
  "Marie Antoinette Fantasy",
  "Carnival Couture",
  "Las Vegas Showgirl",
  "The Roaring 20s",
  "Golden Age of Hollywood",
  "Broadway Diva",
  "Disney Villains Realness",
  "Cartoon Character Couture",
  "Pop Art Extravaganza",
  "Surrealism Fantasy",
  "Drag on Fire",
  "Tropical Goddess",
  "Safari Chic",
  "Pajama Party Realness",
  "Camp Fashion",
  "Comic Book Couture",
  "Moulin Rouge Fantasy",
  "Harajuku Girl",
  "Kawaii Dreamland",
  "Cyberpunk Queen",
  "Dystopian Eleganza",
  "Glam Rock Superstar",
  "Punk Rock Chic",
  "80s Power Diva",
  "90s Supermodel Fantasy",
  "2000s Y2K Glam",
  "Denim & Diamonds",
  "Latex & Leather Fantasy",
  "Mugler Fantasy",
  "Club Kid Couture",
  "Drag Clown Extravaganza",
  "Jungle Fever",
  "Burial Eleganza",
  "Bridezilla Fantasy",
  "Victorian Vampire",
  "Space Age Couture",
  "Circus Freak Realness",
  "Safari Chic",
  "Powerpuff Girls Fantasy",
  "Roller Derby Diva",
  "Androgyny Realness",
  "Fire & Ice Fantasy",
  "Battle Armor Couture",
  "Art Pop Extravaganza",
  "Toxic Waste Couture",
  "Plastic Fantastic",
  "Anime Fantasy",
  "God & Goddesses",
  "Villains of History",
  "Lingerie Fantasy",
  "Royal Wedding Eleganza",
  "Mythical Beasts",
  "Femme Fatale Noir",
  "Electric Glow",
  "Drag Royalty"
]
