export const ruquotes = [
  "\"{name}, tonight may be the end of your journey here, but the world is just beginning to see your magic.\"",
  "\"{name}, you may have lost this battle, but the war for your legacy has only begun.\"",
  "\"{name}, this competition is fierce, but so are you. Never forget that.\"",
  "\"{name}, your time here may be over, but your star is only starting to shine.\"",
  "\"{name}, you may be leaving this stage, but you'll never leave our hearts.\"",
  "\"{name}, drag is not about how you fall, but how you rise. Now go and rise, my dear.\"",
  "\"{name}, remember this: legends aren’t made in one competition, they are made in a lifetime.\"",
  "\"{name}, you showed us your charisma, uniqueness, nerve, and talent. Now, go show the world.\"",
  "\"{name}, your presence lit up this stage, and I know it will light up the world beyond these walls.\"",
  "\"{name}, this may be goodbye for now, but I have a feeling we will meet again.\"",
  "\"{name}, every queen has their time to shine, and I know yours is far from over.\"",
  "\"{name}, you are walking away today, but you will always be part of this family.\"",
  "\"{name}, in the words of a true diva: 'It ain't over till the fat lady sings'. And I don’t hear her yet.\"",
  "\"{name}, this competition may have ended for you, but your journey is just beginning.\"",
  "\"{name}, you are a queen, and queens never truly fall. They just take a new throne elsewhere.\"",
  "\"{name}, your drag is your power. Go out there and use it to change the world.\"",
  "\"{name}, this stage will miss your light, but I know it will shine elsewhere.\"",
  "\"{name}, always remember: it’s not about how many times you fall, but how many times you get back up.\"",
  "\"{name}, keep your head high, your heels higher, and your dreams highest.\"",
  "\"{name}, today may be a loss, but tomorrow is a new victory waiting for you.\"",
  "\"{name}, you've already won by showing the world who you are. Never stop doing that.\"",
  "\"{name}, you may be leaving, but your legacy? That’s forever.\"",
  "\"{name}, you are leaving this competition, but the world is yours to conquer.\"",
  "\"{name}, there is no doubt in my mind that this is not the last we’ve seen of you.\"",
  "\"{name}, remember: you are born to be a star. Go out there and shine.\""
]
