export const ruvision = {
  "Acting Challenge": [
    "Lights, camera… ACTION! But be careful, queens, not every role is a star-making performance. Will you deliver an Oscar-worthy monologue or end up in the cutting room floor?",
    "A wise queen once said: ‘All the world's a stage’... and some of you are just background extras. Let’s see who’s ready for their close-up!",
    "Hollywood is calling, but not every call is a callback. Can you bring the drama, the comedy, and the TEA? Or will you be reading from a one-way script… to elimination?",
    "A great actress can make you laugh, make you cry, and most importantly… make RuPaul clutch her pearls. Now get out there and SHINE, ladies!",
    "From campy sitcoms to high-drama soap operas, this is your chance to prove you're a leading lady, not an understudy!",
    "Darlings, in Hollywood, the difference between an icon and a flop is all in the delivery. So, remember: When in doubt, overact!",
    "Tonight, the Emmy goes to… well, we’ll see about that. Some of you may get a standing ovation, others… a mercy applause.",
    "Good acting is all about chemistry. Bad acting is all about cringe. Let’s see where you land, queens!",
    "This industry is cutthroat, but don’t worry. If you can’t act, at least learn how to fake it!",
    "You don’t need talent to act, just confidence! Now go out there and FAKE IT ‘til you make it!"
  ],
  "Ball Challenge": [
    "Category is: FABULOUS! But queens, if your sewing skills are tragic, you better start praying to the fashion gods RIGHT NOW!",
    "A true queen can turn scraps into showstoppers. And honey, if you can’t sew, you better staple, glue, and PRAY!",
    "Tonight, you’ll be serving THREE unforgettable looks. But remember, darling, one misstep on the runway and it's game over!",
    "Drag and fashion go together like wigs and glue. Let’s see if you can give the judges fashion-forward, not fashion-fail!",
    "Legendary designers start with a single stitch. Some of you may need a miracle instead!",
    "One queen’s trash is another queen’s fashion statement! So, work that needle, because this Ball is about to be LEGENDARY!",
    "The fashion world is fierce, but I hope your outfits are fiercer. Otherwise… let’s just say ‘fashion roadkill’ is a thing.",
    "Are you ready to serve head-to-toe couture realness? Or will your look scream ‘clearance bin’?",
    "Runway to riches or runway to rags? The choice is yours, queens. Let’s get to werk!",
    "Make it work, or make it disappear! Because only one queen can be the Belle of this Ball!"
  ],
  "Choreography Challenge": [
    "Ladies, tonight it’s all about the moves! So, stretch those legs, pop those hips, and try not to trip over your own feet!",
    "They say dancing is just storytelling with your body. Some of you may be giving Shakespeare, others… an interpretive mess.",
    "Can you hit the beat like a pro, or will you be dancing to the sound of your own elimination?",
    "Remember, queens, it’s not just about the moves, it’s about the ATTITUDE! Now get ready to shake, strut, and SERVE!",
    "Some of you will be twirling to victory… and others will be stumbling straight to the bottom!",
    "Drag is about confidence, and nothing tests confidence like a group routine! Let’s see who shines and who just fades into the background!",
    "5, 6, 7, 8! Some of you will SLAY this routine, others will struggle to stay on beat. Either way… it’s going to be a SHOW!",
    "Darlings, if you can’t dance, you better fake it like you’re in a sold-out stadium!",
    "Tonight, you’re not just a queen, you’re a pop star! Now make the audience scream!",
    "You can be out of breath, but never out of face! Let’s see who can werk this stage!"
  ],
  "Snatch Game": [
    "The library is open, because reading is fundamental! But tonight, it’s all about the SNATCH!",
    "Can you make RuPaul laugh until her wig flies off, or will your performance be deader than a celebrity wax figure?",
    "Impersonation is the highest form of flattery… or the quickest way to embarrass yourself on national TV!",
    "Some queens make history in the Snatch Game, others become cautionary tales. Choose wisely!",
    "A bad Snatch Game performance haunts queens FOREVER. So, make it funny, or make an exit plan!",
    "Ladies, if you’re not funny, you better be DELUSIONAL. Let’s see who can sell the fantasy!",
    "The best Snatch Game performances go viral. The worst ones… well, let’s just say, Twitter will have a FIELD DAY!",
    "This is not just about looking like your character, it’s about OWNING the room. So get into character and let’s get funny!",
    "If comedy is about timing, some of you may be running out of time!",
    "Who will make the judges cackle, and who will be left cringing? Let’s find out!"
  ],
  "Talent Show": [
    "Tonight, it’s time to show us what makes you a STAR! Or at least… why you’re still here!",
    "This is your moment! Do you have what it takes to captivate the judges, or will your talent be questionable at best?",
    "Some talents are jaw-dropping, others are head-scratching. Let’s see which one YOU bring to the stage!",
    "Every queen says they have talent… well, now it’s time to PROVE IT!",
    "Welcome to the Drag Race Talent Extravaganza! But remember, darling, bad performances haunt queens FOREVER!",
    "Magic tricks? Stand-up? Singing? We’ve seen it all. The real question is: Will we remember YOUR act?",
    "It’s not just about talent, it’s about CHARISMA. So make it big, make it loud, and MAKE IT MEMORABLE!",
    "Darlings, a great performance can win you this whole competition. A bad one… well, let’s not talk about that!",
    "This is not just another challenge. This is YOUR LEGACY. So, what are you bringing to the stage?",
    "We’ve seen queens soar in the Talent Show… and we’ve seen queens flop HARD. Let’s see which one you are!"
  ],
  "Commercial Challenge": [
    "Tonight, you’re not just queens, you’re business moguls! Can you sell a dream, or will your commercial be a nightmare?",
    "Ladies, in the world of drag, branding is EVERYTHING. If you can’t sell yourself, how do you expect to sell a product?",
    "A good commercial is like a great wig—snatched, polished, and unforgettable. A bad one? Well, let’s just say… it’ll haunt you forever.",
    "Do you have the charisma to sell even the most ridiculous product? Or will your ad be as appealing as expired foundation?",
    "Queens, you’re about to enter the world of advertising. So remember: Keep it catchy, keep it funny, and most importantly… keep it MEMORABLE!",
    "Some commercials sell a fantasy. Others just sell regret. Which one will you be serving today?",
    "The best commercials go viral, the worst ones… end up on the Drag Race blooper reel!",
    "From infomercials to luxury brands, today you need to sell it like your drag career depends on it… because it just might!",
    "Ladies, if you can’t be funny, at least be DELUSIONAL! Let’s see who can make the judges gag for all the right reasons!",
    "They say a picture is worth a thousand words… but a BAD commercial is worth a thousand regrets. Let’s make this one COUNT!"
  ],
  "Design Challenge": [
    "Sewing machines at the ready! Because tonight, it’s all about creativity, construction, and a whole lot of hot glue.",
    "Drag queens are like fashion designers… except with WAY more duct tape. Let’s see who can turn scraps into couture!",
    "In the world of fashion, one day you’re in, and the next day… you’re struggling to sew a hemline!",
    "Can you transform ordinary materials into extraordinary drag? Or will your look scream ‘last-minute craft project’?",
    "A great queen knows how to serve a LOOK. But can you actually MAKE one?",
    "Some of you will create runway magic… and some of you will create fashion disasters. Let’s see which side you’re on!",
    "Remember, queens: Hot glue is a drag queen’s best friend… until it isn’t!",
    "From avant-garde to straight-up bizarre, tonight’s looks need to impress. So thread those needles and start creating!",
    "Fashion is about risk-taking. But let’s make sure your risks don’t lead to a total design MELTDOWN!",
    "Elegance, glamour, and just a hint of desperation… the perfect mix for a design challenge!"
  ],
  "Girl Group Challenge": [
    "It’s time to pop, lock, and serve some sickening vocals… or at least, try your best!",
    "The music industry is cutthroat, and tonight, you’ll find out if you’re a superstar or just a glorified backup dancer.",
    "Some queens will give you Destiny’s Child… others will give you a Destiny’s TRAGEDY.",
    "A true pop diva knows how to command the stage. But can you command a whole GROUP?",
    "Ladies, you’re about to form the hottest new girl group! But remember: A group is only as strong as its weakest link.",
    "Will your group be the next Spice Girls or just… bland and forgettable?",
    "Great girl groups make hits. Bad girl groups make excuses. Which one will you be tonight?",
    "Synchronization, sass, and stage presence—do you have what it takes to make your group a sensation?",
    "Nothing says 'drama' like putting queens together in a girl group. Let’s see who leads and who gets left behind!",
    "The best girl groups make history, the worst ones… make excuses! Let’s see who’s hitting the right notes tonight!"
  ],
  "Improvisation Challenge": [
    "Quick thinking, sharp wit, and NO SCRIPT? Oh honey, some of you are about to sweat!",
    "In drag, sometimes you gotta expect the unexpected… and tonight, EVERYTHING is unexpected!",
    "Some queens rise under pressure, others crumble like bad contour. Let’s see who can werk without a script!",
    "Improvisation is like tucking—if you do it right, no one notices the struggle!",
    "Think fast, act faster, and most importantly… make us LAUGH!",
    "A good improviser can make a mess seem intentional. A bad one? Well… let’s hope you packed your suitcase wisely!",
    "Darlings, it’s not about what happens, it’s about how you REACT!",
    "You don’t need a script to be funny… but some of you might wish you had one!",
    "Some of you will turn this into comedy gold… others will just turn red from embarrassment!",
    "In this challenge, you either steal the spotlight or fade into the background. Which will it be?"
  ],
  "Lip Sync Challenge": [
    "When the music starts, the truth comes out. Can you give us the performance of a lifetime?",
    "Some queens lip sync for their lives… Tonight, EVERY queen is lip syncing for their reputation!",
    "A true queen can turn a song into a MOMENT. Will you have the judges gagging, or just yawning?",
    "The lips may be syncing, but the energy better be REAL!",
    "Drag queens and music go together like wigs and glue—just make sure yours doesn’t come off mid-performance!",
    "Tonight, it’s all about emotion, passion, and just the right amount of hair flips!",
    "Some of you will command the stage, others will get lost in the lyrics!",
    "Will you give us Broadway, music video realness, or just… bad karaoke?",
    "The stage is yours! Now, will you make history or just make RuPaul raise an eyebrow?",
    "Darlings, this is your moment to SHINE! Unless, of course… you forget the words."
  ],
  "Makeover Challenge": [
    "Drag is all about transformation… but can you turn a pumpkin into a princess?",
    "A great queen doesn’t just look fabulous—she can make OTHERS look fabulous too!",
    "They say beauty is in the eye of the beholder… but let’s be real, tonight it’s in the hands of your makeup brush!",
    "Your challenge is to take a blank canvas and turn it into a masterpiece… or at least, something not terrifying.",
    "Will your partner be runway-ready, or will they look like they lost a bet?",
    "Queens, tonight you’re not just competing for yourself—you’re making over someone ELSE! So choose wisely!",
    "A makeover is only as strong as the bond you create. Can you bring your partner into the world of drag?",
    "Some of you will create legendary duos, others… will create disasters!",
    "Drag is a superpower. Tonight, your mission is to share that power with someone new!",
    "Mirror, mirror on the wall… will your makeover be the fiercest of them all?"
  ],
  "Music Video Challenge": [
    "Pop stars, get ready to WERK! Tonight, you’ll be the leading ladies of your very own music video!",
    "Can you serve superstar energy, or will your performance be more ‘one-hit wonder’?",
    "Tonight, you’re not just drag queens—you’re ICONS! Give us charisma, uniqueness, nerve, and TALENT!",
    "Lights, camera, ACTION! But be warned: the camera sees EVERYTHING!",
    "Great music videos are all about ATTITUDE. Will you be unforgettable or just… unwatchable?",
    "Darlings, this is your chance to give us pop diva realness! Just… try not to trip over the choreography!",
    "From slow-motion glamor shots to high-energy performances, tonight you need to SERVE!",
    "Not every queen is a natural pop star… but you better FAKE IT ‘til you MAKE IT!",
    "They say music videos make stars… but bad ones? Well, they make memes.",
    "Get ready for glitter, drama, and just the right amount of overacting!"
  ],
  "Photoshoot Challenge": [
    "One frame, one moment, one shot at glory—will you be picture-perfect?",
    "In drag, every angle matters… and the camera NEVER lies!",
    "Can you find your light, serve face, and give editorial realness? Or will you be a lighting disaster?",
    "A great photo tells a story. Let’s just hope yours isn’t a tragic one!",
    "They say the camera adds ten pounds. Honey, let’s make sure it adds ten pounds of FABULOUSNESS!",
    "Serving supermodel fantasy or awkward yearbook photo? Let’s find out!",
    "Darlings, every blink, every smirk, every pose—it ALL matters! Don’t waste a single frame!",
    "One click and your legacy is sealed… make sure it’s a good one!",
    "Not all queens are natural models, but tonight, you better become one!",
    "Pose, smize, and WORK! Because bad pictures last FOREVER!"
  ],
  "Rumix Challenge": [
    "Tonight, you’re remixing a RuPaul classic! Will you make it legendary or forgettable?",
    "Queens, tonight you don’t just need to perform, you need to REINVENT!",
    "Some queens will turn this song into a masterpiece… others will turn it into a disaster!",
    "A great remix needs energy, originality, and just a hint of DRAMA!",
    "You better know your lyrics, queens, because tonight, the stage is YOURS!",
    "It’s time to bring the beat, the moves, and the ATTITUDE!",
    "A remix can make a song better… or ruin it completely. Let’s see what YOU do!",
    "Will your performance have the judges dancing, or just confused?",
    "Get ready to WERK it out, because this remix challenge is EVERYTHING!",
    "Darlings, make it loud, make it proud, and most importantly—make it ICONIC!"
  ],
  "Runway Challenge": [
    "Ladies, the runway is calling… and only the fiercest will answer!",
    "This is not just a walk, this is a STATEMENT. Now go out there and OWN IT!",
    "Some queens will serve glamour, others will serve confusion. Let’s see what YOU bring!",
    "Fashion is all about risk… but make sure your risks don’t turn into REGRETS!",
    "Turn heads, drop jaws, and most importantly—DON’T FALL!",
    "A great runway walk is like a perfect tuck: smooth, effortless, and jaw-dropping!",
    "Tonight, you are THE moment. So give the judges something to remember!",
    "Drag and fashion are all about fantasy. Will you be a dream… or a nightmare?",
    "One step at a time, queens… and make each one COUNT!",
    "When you hit that runway, don’t just walk—SERVE!"
  ],
  "Rusical Challenge": [
    "Tonight, we’re taking Broadway, flipping it on its head, and adding a WHOLE lot of glitter! Will you be a star… or a stagehand?",
    "The stage is set, the lights are on, and the only thing missing is a show-stopping performance. Don’t let this be a one-act disaster!",
    "Can you hit the high notes and land the choreography, or will you be giving ‘off-off-off Broadway’ realness?",
    "Some queens will take center stage… others will struggle to find their light!",
    "Drag queens and musicals go together like wigs and glue. But will your performance hold up, or will it fall apart at the seams?",
    "From camp to drama, from comedy to tragedy, tonight is your chance to prove you’re more than just a pretty face!",
    "Get ready to sing, dance, and most importantly… keep up! Because in a Rusical, timing is EVERYTHING!",
    "A great performance can win you this competition. A bad one? Well, let’s just say… some flops last forever.",
    "Theatre kids, rise up! And for the rest of you… good luck, you’ll need it!",
    "Whether you’re the leading lady or just a background dancer, make EVERY moment count!"
  ],
  "Singing Challenge": [
    "Queens, tonight you’re not just lip-syncing… you’re SINGING! So warm up those vocal cords and pray for the best!",
    "Some of you will give us Mariah, others will give us… well, let’s hope you don’t give us nails on a chalkboard!",
    "A true queen can command the stage with nothing but her voice. Will you be music to our ears, or just another off-key tragedy?",
    "Tonight, you’ll be stepping into the recording booth, and let me tell you… Autotune can only do so much!",
    "Some of you will be hitting high notes, others… might be hitting the road. Let’s hope it’s the first one!",
    "Drag queens and divas go hand in hand. But will you be a legend or a one-hit wonder?",
    "From power ballads to club bangers, tonight it’s all about the VOCALS!",
    "Singing live takes talent, charisma, and confidence. If you don’t have at least two of those… you’re in trouble!",
    "The world loves a drag queen with pipes! So, let’s hope yours don’t BURST!",
    "Channel your inner pop star and make the judges gag… in a GOOD way!"
  ],
  "Stand-Up Challenge": [
    "Ladies, the microphone is on, the audience is waiting… and comedy is HARD. Let’s see who can bring the laughs!",
    "They say laughter is the best medicine, but a bad joke can be a DEATH sentence. Let’s hope your set is more legendary than tragic!",
    "A great queen can make the audience GAG… but can you make them LAUGH?",
    "Comedy queens, this is your time to SHINE! And for the rest of you… may I suggest praying?",
    "The best stand-up comedians can turn anything into a joke. The worst ones… well, they BECOME the joke.",
    "Some queens will leave the judges in stitches, others will leave them checking the time. Let’s hope you’re in the first group!",
    "Timing, delivery, and punchlines—get them right, and you’ll be a star. Get them wrong… and you’ll be hearing crickets!",
    "Drag queens and comedy go together like bad contour and harsh lighting. Let’s see who can make it work!",
    "Can you hold an audience’s attention, or will you be watching your jokes BOMB in real time?",
    "A great joke can win you the night. A bad one? Well, let’s just say… you might wanna start packing!"
  ]
}